services:
  # AgentaFlow Web Dashboard - Using latest built image
  agentaflow-dashboard:
    image: ghcr.io/finoptimize/agentaflow-sro-community:web-dashboard-latest
    container_name: agentaflow-dashboard-test
    ports:
      - "9000:9000"  # Web Dashboard
      - "9001:9001"  # Prometheus Metrics
    environment:
      - LOG_LEVEL=debug
      - GPU_SIMULATION=true
      - ALERT_THRESHOLDS=temperature:80,utilization:95,memory:90
      - CI_MODE=true
    networks:
      - agentaflow-test
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: agentaflow-prometheus-test
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/rules:/etc/prometheus/rules:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=1h'
      - '--web.enable-lifecycle'
      - '--log.level=info'
    networks:
      - agentaflow-test
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  agentaflow-test:
    driver: bridge
    name: agentaflow-test-network
