---
apiVersion: v1
kind: Namespace
metadata:
  name: agentaflow
  labels:
    name: agentaflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentaflow-scheduler
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["nodes/status", "pods/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentaflow-scheduler
  namespace: agentaflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agentaflow-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agentaflow-scheduler
subjects:
- kind: ServiceAccount
  name: agentaflow-scheduler
  namespace: agentaflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentaflow-gpu-scheduler
  namespace: agentaflow
  labels:
    app: agentaflow-gpu-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentaflow-gpu-scheduler
  template:
    metadata:
      labels:
        app: agentaflow-gpu-scheduler
    spec:
      serviceAccountName: agentaflow-scheduler
      containers:
      - name: scheduler
        image: agentaflow/k8s-gpu-scheduler:latest
        args:
        - --mode=scheduler
        - --namespace=agentaflow
        - --strategy=least_utilized
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agentaflow-gpu-monitor
  namespace: agentaflow
  labels:
    app: agentaflow-gpu-monitor
spec:
  selector:
    matchLabels:
      app: agentaflow-gpu-monitor
  template:
    metadata:
      labels:
        app: agentaflow-gpu-monitor
    spec:
      serviceAccountName: agentaflow-scheduler
      hostPID: true
      containers:
      - name: monitor
        image: agentaflow/k8s-gpu-scheduler:latest
        args:
        - --mode=monitor
        - --namespace=agentaflow
        - --node=$(NODE_NAME)
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          privileged: true
        volumeMounts:
        - name: nvidia-driver
          mountPath: /usr/local/nvidia
          readOnly: true
        - name: dev
          mountPath: /dev
      volumes:
      - name: nvidia-driver
        hostPath:
          path: /usr/local/nvidia
      - name: dev
        hostPath:
          path: /dev
      nodeSelector:
        agentaflow.gpu/enabled: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: agentaflow-scheduler-service
  namespace: agentaflow
  labels:
    app: agentaflow-gpu-scheduler
spec:
  selector:
    app: agentaflow-gpu-scheduler
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP